### PR TITLE
chore(ci): remove Mergify

### PR DESCRIPTION
**Pull request by xiehan**
Replace it with custom auto-approve and automerge workflows. Also updates all of our GitHub Actions to using pinned SHA hashes.

### CODE REVIEW

**Review by Maed223 — COMMENTED** [review]
Quick question on the new `auto-approve` workflow, how exactly is checking that the CI is green? Something to do with the types on `pull_request_target`?

**Comment by xiehan** [comment]
> Quick question on the new `auto-approve` workflow, how exactly is checking that the CI is green? Something to do with the types on `pull_request_target`?

The auto-approve workflow isn't checking that at all. All that one does is check to see if the "auto-approve" label was added to the PR and if it was, one of the bot accounts (either team-tf-cdk or github-actions[bot]) will approve the PR.

The new automerge workflow is the one that's implicitly doing that. See the [docs](https://cli.github.com/manual/gh_pr_merge) for `gh pr merge`:

> `--auto`
>   Automatically merge only after necessary requirements are met

What this is doing is using GitHub's built in [automerge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request) feature. This is a relatively new feature that was only added in the past year, hence why so many 3rd party tools like Mergify exist. They were filling a void before GitHub added support for this natively.

**Comment by mutahhir** [comment]
A follow up question to @Maed223, I think the automerge queue will only wait for the approval and not for the CI tests. That's happening on our terraform-cdk repo as well. I found [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group) that should help if we add the `merge_group` field to `build` and other required check workflows. I also haven't tested this, so I may be wrong on this.

**Comment by mutahhir** [comment]
I'm going to approve so you're not blocked, and it's fine to experiment a bit on this one I think.

**Review by mutahhir — APPROVED** [review]

**Comment by xiehan** [comment]
> A follow up question to @Maed223, I think the automerge queue will only wait for the approval and not for the CI tests. That's happening on our terraform-cdk repo as well. I found [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group) that should help if we add the `merge_group` field to `build` and other required check workflows. I also haven't tested this, so I may be wrong on this.

I suspect that that may be because the `terraform-cdk` repo doesn't have any status checks that are marked as required; this one does. As you've noted, there's no way to really verify without merging and testing it out, so I'll merge this and try it with my other PR to see what happens.

**Pull request merged**
